### ISSUE TITLE
Full taxonomy doesn't work

### ISSUE THREAD

**Issue by Chabname** [AuReMe/emapper2gbk#9]
* eggnog2gbk version:
* Python version:
* Operating System:

### Description
On directory mode, when we give a file with taxonomy values, having the full taxonomy and not the specie, the program only get the first value. 
I'm going to create a branch and propose a modification

### What I Did

```
Example :
    Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacterales;Enterobacteriaceae;Escherichia;Escherichia marmotae
The taxon find is for "Bacteria".
If we reverse it, it will find the taxon for "Escherichia marmotae"
If the first element is not found (because does not exist) it will not try to find the parent.
```

**Comment by ArnaudBelcour** [comment]
Added in [0.2.0](https://github.com/AuReMe/emapper2gbk/releases/tag/0.2.0).
